# Generated by Django 2.0.4 on 2018-04-29 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentorSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mentorskills', models.CharField(choices=[('Empty', 'Please select skill(s)'), ('Artificial Intelligence', 'ArtificialIntelligence'), ('DataAnalysis', 'Data Analysis'), ('Presentation Skills', 'Presentation Skills'), ('Communication', 'Communication'), ('Python', 'Python'), ('Database', 'Database'), ('UX Design', 'UX Design'), ('Project Management', 'Project Management'), ('Portfolio Management', 'Portfolio Management'), ('Investment Systems', 'Investment Systems'), ('Leadership Skill', 'Leadership Skill')], default='Empty', max_length=30)),
                ('Mentorskill_level', models.CharField(choices=[('Empty', 'Please select skill level '), ('Advanced', 'Advanced'), ('Intermediate ', 'Intermediate'), ('Beginner', 'Beginner')], default='Empty', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=20)),
                ('last_Name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mentor', models.BooleanField()),
                ('mentee', models.BooleanField()),
                ('virtual_Mentorship', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='YES', max_length=10)),
                ('number_of_Mentees', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (5, 5)], default=1)),
                ('Other_Interests', models.TextField(max_length=500, null=True)),
                ('Living_Our_Purpose', models.CharField(choices=[('Empty', 'Please select a Purpose questions'), ('As a BLK employee, where can you have the biggest impact on society?', 'As a BLK employee,where can you have the biggest impact on society'), ('What is your personal definition of wellbeing?', 'What is your personal definition of wellbeing?'), ('Where do you believe BlackRock can have the biggest impact on society?', 'Where do you believe BlackRock can have the biggest impact on society?'), ("Tell me about a unique area of expertise that you're proud of", "Tell me about a unique area of expertise that you're proud of"), ('What makes you most proud to be a part of BlackRock?', 'What makes you most prod to be a part of BlackRock?'), ('What do you most want people to know about BlackRock?', 'What do you most want people to know about BlackRock?')], default='Empty', max_length=300)),
                ('Ans', models.TextField(max_length=50, null=True)),
                ('Mentee_Skills', models.CharField(choices=[("What are the new areas of expertise that you're trying to develop?", "What are the new areas of expertise that you're trying to develop?")], default='Empty', max_length=300)),
                ('Artificial_Intelligence', models.BooleanField()),
                ('Data_Analysis', models.BooleanField()),
                ('Presentation_Skills', models.BooleanField()),
                ('Communication', models.BooleanField()),
                ('Python', models.BooleanField()),
                ('Database', models.BooleanField()),
                ('UX_Design', models.BooleanField()),
                ('Project_Management', models.BooleanField()),
                ('Portfolio_Management', models.BooleanField()),
                ('Investment_Systems', models.BooleanField()),
                ('Leadership_Skill', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='mentorskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mentorlist', to='MatchBLK.SignUp'),
        ),
    ]
